### PR TITLE
conf: Align layer name to directory name

### PR DESCRIPTION
**Pull request by rzr**
Rename layer name to "iot-web from "iotweb", to be used in collections.

This way this layer can be optionally and dynamicaly overloaded by sub layer,
using this scriplet:

  BBFILES += "${@' '.join('${LAYERDIR}/meta-%s/recipes*/*/*.bb' % layer \
  for layer in BBFILE_COLLECTIONS.split())}"

Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>
Origin: https://github.com/ostroproject/meta-iot-web/pull/47

### CODE REVIEW

**Comment by rzr** [comment]
As suggested by @pohly , note I am not sure this layer collection repo is very convenient, some scripts are pulling meta-layers using scripts and git, having them separated like original meta-iot-web will help smooth transitions if layer is pulled out ostro main project.

**Comment by pohly** [comment]
It's not uncommon to have multiple layers in a single repo. meta-openembedded is the prime example, meta-security recently started doing it. Whatever tools people use, they should be prepared for this case.

**Comment by rzr** [comment]
I will adapt, but your examples are layers, is iot-web-layers supposed to become a layer too ? in that case maybe it could be renamed to meta-iot-web-layer*s* ?
Maybe I should open an issue about that specific question, since this change is not related to the discussion I justed started.

**Comment by pohly** [comment]
On Tue, 2017-07-18 at 06:24 -0700, rzr wrote:
> I will adapt, but your examples are layers

No, meta-openembedded is not a layer. It's a repo containing layers,
just like iot-web-layers. One could argue that it then shouldn't be
called *meta*-openembedded, but there is no enforced policy about naming
repos or even layers.

**Comment by nagineni** [comment]
+1

**Pull request merged**
